JANUS=/var/www/html/janus/schedule_files

default: \
	$(JANUS)/all.js \
	$(JANUS)/breakoutRoomDialog.js \
	$(JANUS)/combobox.js \
	$(JANUS)/date_time.js \
	$(JANUS)/date_time_common.js \
	$(JANUS)/embed.js \
	$(JANUS)/form_custom.js \
	$(JANUS)/interpretation.js \
	$(JANUS)/jquery-datepicker-acc.js \
	$(JANUS)/jquery-ui.js \
	$(JANUS)/jquery.js \
	$(JANUS)/lodash.js \
	$(JANUS)/meeting-vue.js \
	$(JANUS)/meetings.js \
	$(JANUS)/member_add.js \
	$(JANUS)/new_recurrence_tools.js \
	$(JANUS)/notification.js \
	$(JANUS)/password.js \
	$(JANUS)/pbxSideMenu.js \
	$(JANUS)/popup-captcha.js \
	$(JANUS)/public_calendar_warning.js \
	$(JANUS)/select2.js \
	$(JANUS)/snippet.js \
	$(JANUS)/upload.js \
	$(JANUS)/vue-dragging.js \
	$(JANUS)/vue.js \
	$(JANUS)/wootric-sdk.js \
	$(JANUS)/zoom-components.js \
	$(JANUS)/zoom_plugin.js \
	$(JANUS)/all.css \
	$(JANUS)/common.css \
	$(JANUS)/common4whenAndDuring.css \
	$(JANUS)/form_layout.css \
	$(JANUS)/jquery-ui.css \
	$(JANUS)/meeting.css \
	$(JANUS)/meeting4interpretation.css \
	$(JANUS)/meeting_delete_dialog.css \
	$(JANUS)/notification.css \
	$(JANUS)/popup-captcha.css \
	$(JANUS)/reset.css \
	$(JANUS)/select2.css \
	$(JANUS)/style.css \
	$(JANUS)/unite-style-for-form.css \
	$(JANUS)/upload.css \
	$(JANUS)/zm-vue-component.css \
	$(JANUS)/zoom-components.css \
	$(JANUS)/ZoomLogo.png \
	$(JANUS)/i_add_member.png \
	$(JANUS)/i_bookmarkfolder.png \
	$(JANUS)/i_bookmarkfolder_open.png \
	$(JANUS)/i_delete.png \
	$(JANUS)/icon_clicked.png \
	$(JANUS)/img_checkbox_off.png \
	$(JANUS)/img_checkbox_on.png \
	$(JANUS)/pay_us_meow.png \
	$(JANUS)/social_icon.png \
	$(JANUS)/user.png \
	$(JANUS)/csrf_js

$(JANUS)/all.js: all.js
	sudo cp all.js $(JANUS)/
$(JANUS)/breakoutRoomDialog.js: breakoutRoomDialog.js
	sudo cp breakoutRoomDialog.js $(JANUS)/
$(JANUS)/combobox.js: combobox.js
	sudo cp combobox.js $(JANUS)/
$(JANUS)/date_time.js: date_time.js
	sudo cp date_time_common.js $(JANUS)/
$(JANUS)/date_time_common.js: date_time_common.js
	sudo cp date_time.js $(JANUS)/
$(JANUS)/embed.js: embed.js
	sudo cp embed.js $(JANUS)/
$(JANUS)/form_custom.js: form_custom.js
	sudo cp form_custom.js $(JANUS)/
$(JANUS)/interpretation.js: interpretation.js
	sudo cp interpretation.js $(JANUS)/
$(JANUS)/jquery-datepicker-acc.js: jquery-datepicker-acc.js
	sudo cp jquery-datepicker-acc.js $(JANUS)/
$(JANUS)/jquery-ui.js: jquery-ui.js
	sudo cp jquery-ui.js $(JANUS)/
$(JANUS)/jquery.js: jquery.js
	sudo cp jquery.js $(JANUS)/
$(JANUS)/lodash.js: lodash.js
	sudo cp lodash.js $(JANUS)/
$(JANUS)/meeting-vue.js: meeting-vue.js
	sudo cp meeting-vue.js $(JANUS)/
$(JANUS)/meetings.js: meetings.js
	sudo cp meetings.js $(JANUS)/
$(JANUS)/member_add.js: member_add.js
	sudo cp member_add.js $(JANUS)/
$(JANUS)/new_recurrence_tools.js: new_recurrence_tools.js
	sudo cp new_recurrence_tools.js $(JANUS)/
$(JANUS)/notification.js: notification.js
	sudo cp notification.js $(JANUS)/
$(JANUS)/password.js: password.js
	sudo cp password.js $(JANUS)/
$(JANUS)/pbxSideMenu.js: pbxSideMenu.js
	sudo cp pbxSideMenu.js $(JANUS)/
$(JANUS)/popup-captcha.js: popup-captcha.js
	sudo cp popup-captcha.js $(JANUS)/
$(JANUS)/public_calendar_warning.js: public_calendar_warning.js
	sudo cp public_calendar_warning.js $(JANUS)/
$(JANUS)/select2.js: select2.js
	sudo cp select2.js $(JANUS)/
$(JANUS)/snippet.js: snippet.js
	sudo cp snippet.js $(JANUS)/
$(JANUS)/upload.js: upload.js
	sudo cp upload.js $(JANUS)/
$(JANUS)/vue-dragging.js: vue-dragging.js
	sudo cp vue-dragging.js $(JANUS)/
$(JANUS)/vue.js: vue.js
	sudo cp vue.js $(JANUS)/
$(JANUS)/wootric-sdk.js: wootric-sdk.js
	sudo cp wootric-sdk.js $(JANUS)/
$(JANUS)/zoom-components.js: zoom-components.js
	sudo cp zoom-components.js $(JANUS)/
$(JANUS)/zoom_plugin.js: zoom_plugin.js
	sudo cp zoom_plugin.js $(JANUS)/
$(JANUS)/all.css: all.css
	sudo cp all.css $(JANUS)/
$(JANUS)/common.css: common.css
	sudo cp common.css $(JANUS)/
$(JANUS)/common4whenAndDuring.css: common4whenAndDuring.css
	sudo cp common4whenAndDuring.css $(JANUS)/
$(JANUS)/form_layout.css: form_layout.css
	sudo cp form_layout.css $(JANUS)/
$(JANUS)/jquery-ui.css: jquery-ui.css
	sudo cp jquery-ui.css $(JANUS)/
$(JANUS)/meeting.css: meeting.css
	sudo cp meeting.css $(JANUS)/
$(JANUS)/meeting4interpretation.css: meeting4interpretation.css
	sudo cp meeting4interpretation.css $(JANUS)/
$(JANUS)/meeting_delete_dialog.css: meeting_delete_dialog.css
	sudo cp meeting_delete_dialog.css $(JANUS)/
$(JANUS)/notification.css: notification.css
	sudo cp notification.css $(JANUS)/
$(JANUS)/popup-captcha.css: popup-captcha.css
	sudo cp popup-captcha.css $(JANUS)/
$(JANUS)/reset.css: reset.css
	sudo cp reset.css $(JANUS)/
$(JANUS)/select2.css: select2.css
	sudo cp select2.css $(JANUS)/
$(JANUS)/style.css: style.css
	sudo cp style.css $(JANUS)/
$(JANUS)/unite-style-for-form.css: unite-style-for-form.css
	sudo cp unite-style-for-form.css $(JANUS)/
$(JANUS)/upload.css: upload.css
	sudo cp upload.css $(JANUS)/
$(JANUS)/zm-vue-component.css:
	sudo cp zm-vue-component.css $(JANUS)/
$(JANUS)/zoom-components.css: zoom-components.css
	sudo cp zoom-components.css $(JANUS)/
$(JANUS)/ZoomLogo.png: ZoomLogo.png
	sudo cp ZoomLogo.png $(JANUS)/
$(JANUS)/i_add_member.png: i_add_member.png
	sudo cp i_add_member.png $(JANUS)/
$(JANUS)/i_bookmarkfolder.png: i_bookmarkfolder.png
	sudo cp i_bookmarkfolder.png $(JANUS)/
$(JANUS)/i_bookmarkfolder_open.png: i_bookmarkfolder_open.png
	sudo cp i_bookmarkfolder_open.png $(JANUS)/
$(JANUS)/i_delete.png: i_delete.png
	sudo cp i_delete.png $(JANUS)/
$(JANUS)/icon_clicked.png: icon_clicked.png
	sudo cp icon_clicked.png $(JANUS)/
$(JANUS)/img_checkbox_off.png: img_checkbox_off.png
	sudo cp img_checkbox_off.png $(JANUS)/
$(JANUS)/img_checkbox_on.png: img_checkbox_on.png
	sudo cp img_checkbox_on.png $(JANUS)/
$(JANUS)/pay_us_meow.png: pay_us_meow.png
	sudo cp pay_us_meow.png $(JANUS)/
$(JANUS)/social_icon.png: social_icon.png
	sudo cp social_icon.png $(JANUS)/
$(JANUS)/user.png: user.png
	sudo cp user.png $(JANUS)/
$(JANUS)/csrf_js: csrf_js
	sudo cp csrf_js $(JANUS)/
