JANUS=/var/www/html/janus/images

default: \
	$(JANUS)/Add_a_question.png \
	$(JANUS)/LiveStreaming.png \
	$(JANUS)/Welcome_Hold.png \
	$(JANUS)/Workplace.png \
	$(JANUS)/YouTube.png \
	$(JANUS)/ZoomAppIcon.png \
	$(JANUS)/alert.png \
	$(JANUS)/arrow_down.png \
	$(JANUS)/arrow_updown.png \
	$(JANUS)/camera.png \
	$(JANUS)/cdn-detect.png \
	$(JANUS)/close_cross_icon.png \
	$(JANUS)/cnmeeting.png \
	$(JANUS)/custom.png \
	$(JANUS)/display_bg.png \
	$(JANUS)/display_camera.png \
	$(JANUS)/edit_polls.png \
	$(JANUS)/enabled.png \
	$(JANUS)/fLive.png \
	$(JANUS)/gcal.png \
	$(JANUS)/ical.png \
	$(JANUS)/ico_bidModal_hide_L.png \
	$(JANUS)/icons8-info.svg \
	$(JANUS)/inmeeting.png \
	$(JANUS)/inprogress.png \
	$(JANUS)/large_icon.png \
	$(JANUS)/loading.gif \
	$(JANUS)/loading_16.gif \
	$(JANUS)/loading_24.gif \
	$(JANUS)/login_source@2x.png \
	$(JANUS)/menu_3_line.png \
	$(JANUS)/no.png \
	$(JANUS)/on-demand_webinar.png \
	$(JANUS)/online.png \
	$(JANUS)/pacmeeting.png \
	$(JANUS)/phone.png \
	$(JANUS)/plugin_sprite.png \
	$(JANUS)/progress_bar.png \
	$(JANUS)/progress_bar_handler.png \
	$(JANUS)/progressbar.gif \
	$(JANUS)/rec-start-300x300.png \
	$(JANUS)/rec-stop.png \
	$(JANUS)/recording.png \
	$(JANUS)/recurring_icons.png \
	$(JANUS)/select2.png \
	$(JANUS)/select2x2.png \
	$(JANUS)/share-ico-mobile.png \
	$(JANUS)/sort.png \
	$(JANUS)/user.png \
	$(JANUS)/warning.png \
	$(JANUS)/ycal.png

$(JANUS)/Add_a_question.png: Add_a_question.png
	sudo cp Add_a_question.png $(JANUS)/
$(JANUS)/LiveStreaming.png: LiveStreaming.png
	sudo cp LiveStreaming.png $(JANUS)/
$(JANUS)/Welcome_Hold.png: Welcome_Hold.png
	sudo cp Welcome_Hold.png $(JANUS)/
$(JANUS)/Workplace.png: Workplace.png
	sudo cp Workplace.png $(JANUS)/
$(JANUS)/YouTube.png: YouTube.png
	sudo cp YouTube.png $(JANUS)/
$(JANUS)/ZoomAppIcon.png: ZoomAppIcon.png
	sudo cp ZoomAppIcon.png $(JANUS)/
$(JANUS)/alert.png: alert.png
	sudo cp alert.png $(JANUS)/
$(JANUS)/arrow_down.png: arrow_down.png
	sudo cp arrow_down.png $(JANUS)/
$(JANUS)/arrow_updown.png: arrow_updown.png
	sudo cp arrow_updown.png $(JANUS)/
$(JANUS)/camera.png: camera.png
	sudo cp camera.png $(JANUS)/
$(JANUS)/cdn-detect.png: cdn-detect.png
	sudo cp cdn-detect.png $(JANUS)/
$(JANUS)/close_cross_icon.png: close_cross_icon.png
	sudo cp close_cross_icon.png $(JANUS)/
$(JANUS)/cnmeeting.png: cnmeeting.png
	sudo cpcnmeeting.png $(JANUS)/
$(JANUS)/custom.png: custom.png
	sudo cp custom.png $(JANUS)/
$(JANUS)/display_bg.png: display_bg.png
	sudo cp display_bg.png $(JANUS)/
$(JANUS)/display_camera.png: display_camera.png
	sudo cp display_camera.png $(JANUS)/
$(JANUS)/edit_polls.png: edit_polls.png
	sudo cp edit_polls.png $(JANUS)/
$(JANUS)/enabled.png: enabled.png
	sudo cp enabled.png $(JANUS)/
$(JANUS)/fLive.png: fLive.png
	sudo cp fLive.png $(JANUS)/
$(JANUS)/gcal.png: gcal.png
	sudo cp gcal.png $(JANUS)/
$(JANUS)/ical.png: ical.png
	sudo cp ical.png $(JANUS)/
$(JANUS)/ico_bidModal_hide_L.png: ico_bidModal_hide_L.png
	sudo cp ico_bidModal_hide_L.png $(JANUS)/
$(JANUS)/icons8-info.svg: icons8-info.svg
	sudo cp icons8-info.svg $(JANUS)/
$(JANUS)/inmeeting.png: inmeeting.png
	sudo cp inmeeting.png $(JANUS)/
$(JANUS)/inprogress.png: inprogress.png
	sudo cp inprogress.png $(JANUS)/
$(JANUS)/large_icon.png: large_icon.png
	sudo cp large_icon.png $(JANUS)/
$(JANUS)/loading.gif: loading.gif
	sudo cp loading.gif $(JANUS)/
$(JANUS)/loading_16.gif: loading_16.gif
	sudo cp loading_16.gif $(JANUS)/
$(JANUS)/loading_24.gif: loading_24.gif
	sudo cp loading_24.gif $(JANUS)/
$(JANUS)/login_source@2x.png: login_source@2x.png
	sudo cp login_source@2x.png $(JANUS)/
$(JANUS)/menu_3_line.png: menu_3_line.png
	sudo cp menu_3_line.png $(JANUS)/
$(JANUS)/no.png: no.png
	sudo cp no.png $(JANUS)/
$(JANUS)/on-demand_webinar.png: on-demand_webinar.png
	sudo cp on-demand_webinar.png $(JANUS)/
$(JANUS)/online.png: online.png
	sudo cp online.png $(JANUS)/
$(JANUS)/pacmeeting.png: pacmeeting.png
	sudo cp pacmeeting.png $(JANUS)/
$(JANUS)/phone.png: phone.png
	sudo cp phone.png $(JANUS)/
$(JANUS)/plugin_sprite.png: plugin_sprite.png
	sudo cp plugin_sprite.png $(JANUS)/
$(JANUS)/progress_bar.png: progress_bar.png
	sudo cp progress_bar.png $(JANUS)/
$(JANUS)/progress_bar_handler.png: progress_bar_handler.png
	sudo cp progress_bar_handler.png $(JANUS)/
$(JANUS)/progressbar.gif: progressbar.gif
	sudo cp progressbar.gif $(JANUS)/
$(JANUS)/rec-start-300x300.png: rec-start-300x300.png
	sudo cp rec-start-300x300.png $(JANUS)/
$(JANUS)/rec-stop.png: rec-stop.png
	sudo cp rec-stop.png $(JANUS)/
$(JANUS)/recording.png: recording.png
	sudo cp recording.png $(JANUS)/
$(JANUS)/recurring_icons.png: recurring_icons.png
	sudo cp recurring_icons.png $(JANUS)/
$(JANUS)/select2.png: select2.png
	sudo cp select2.png $(JANUS)/
$(JANUS)/select2x2.png: select2x2.png
	sudo cp select2x2.png $(JANUS)/
$(JANUS)/share-ico-mobile.png: share-ico-mobile.png
	sudo cp share-ico-mobile.png $(JANUS)/
$(JANUS)/sort.png: sort.png
	sudo cp sort.png $(JANUS)/
$(JANUS)/user.png: user.png
	sudo cp user.png $(JANUS)/
$(JANUS)/warning.png: warning.png
	sudo cp warning.png $(JANUS)/
$(JANUS)/ycal.png: ycal.png
	sudo cp ycal.png $(JANUS)/
