JANUS=/var/www/html/janus/fonts

default: \
	$(JANUS)/glyphicons-halflings-regular.eot \
	$(JANUS)/glyphicons-halflings-regular.svg \
	$(JANUS)/glyphicons-halflings-regular.ttf \
	$(JANUS)/glyphicons-halflings-regular.woff

$(JANUS)/glyphicons-halflings-regular.eot: glyphicons-halflings-regular.eot
	sudo cp glyphicons-halflings-regular.eot $(JANUS)/
$(JANUS)/glyphicons-halflings-regular.svg: glyphicons-halflings-regular.svg
	sudo cp glyphicons-halflings-regular.svg $(JANUS)/
$(JANUS)/glyphicons-halflings-regular.ttf: glyphicons-halflings-regular.ttf
	sudo cp glyphicons-halflings-regular.ttf $(JANUS)/
$(JANUS)/glyphicons-halflings-regular.woff: glyphicons-halflings-regular.woff
	sudo cp glyphicons-halflings-regular.woff $(JANUS)/
