JANUS=/var/www/html/janus/css

default: $(JANUS)/bootstrap.css $(JANUS)/demo.css $(JANUS)/font-awesome.css $(JANUS)/toastr.css

$(JANUS)/bootstrap.css: bootstrap.css
	sudo cp bootstrap.css $(JANUS)/
$(JANUS)/demo.css: demo.css
	sudo cp demo.css $(JANUS)/
$(JANUS)/font-awesome.css: font-awesome.css
	sudo cp font-awesome.css $(JANUS)/
$(JANUS)/toastr.css: toastr.css
	sudo cp toastr.css $(JANUS)/
