JANUS=/var/www/html/janus/models/languages

default: \
	$(JANUS)/en.php \
	$(JANUS)/ja.php

$(JANUS)/en.php: en.php
	sudo cp en.php $(JANUS)/
$(JANUS)/ja.php: ja.php
	sudo cp ja.php $(JANUS)/
