HOTROOM=/var/www/html/hotroom/audio

default: $(HOTROOM)/household_telephone_digital_ring_002.mp3 $(HOTROOM)/household_telephone_digital_ring_back.mp3

$(HOTROOM)/household_telephone_digital_ring_002.mp3: household_telephone_digital_ring_002.mp3
	sudo cp household_telephone_digital_ring_002.mp3 $(HOTROOM)/
$(HOTROOM)/household_telephone_digital_ring_back.mp3: household_telephone_digital_ring_back.mp3
	sudo cp household_telephone_digital_ring_back.mp3 $(HOTROOM)/
