JANUS=/var/www/html/janus/meeting_files

default: \
	$(JANUS)/all.js \
	$(JANUS)/embed.js \
	$(JANUS)/jquery.js \
	$(JANUS)/meetings.js \
	$(JANUS)/notification.js \
	$(JANUS)/pbxSideMenu.js \
	$(JANUS)/popup-captcha.js \
	$(JANUS)/select2.js \
	$(JANUS)/snippet.js \
	$(JANUS)/vue.js \
	$(JANUS)/wootric-sdk.js \
	$(JANUS)/zoom-components.js \
	$(JANUS)/all.css \
	$(JANUS)/meeting_delete_dialog.css \
	$(JANUS)/meetings.css \
	$(JANUS)/notification.css \
	$(JANUS)/popup-captcha.css \
	$(JANUS)/select2.css \
	$(JANUS)/zoom-components.css \
	$(JANUS)/RoomLogo.png \
	$(JANUS)/ZoomLogo.png \
	$(JANUS)/pay_us_meow.png \
	$(JANUS)/user.png

$(JANUS)/all.js: all.js
	sudo cp all.js $(JANUS)/
$(JANUS)/embed.js: embed.js
	sudo cp embed.js $(JANUS)/
$(JANUS)/jquery.js: jquery.js
	sudo cp jquery.js $(JANUS)/
$(JANUS)/meetings.js: meetings.js
	sudo cp meetings.js $(JANUS)/
$(JANUS)/notification.js: notification.js
	sudo cp notification.js $(JANUS)/
$(JANUS)/pbxSideMenu.js: pbxSideMenu.js
	sudo cp pbxSideMenu.js $(JANUS)/
$(JANUS)/popup-captcha.js: popup-captcha.js
	sudo cp popup-captcha.js $(JANUS)/
$(JANUS)/select2.js: select2.js
	sudo cp select2.js $(JANUS)/
$(JANUS)/snippet.js: snippet.js
	sudo cp snippet.js $(JANUS)/
$(JANUS)/vue.js: vue.js
	sudo cp vue.js $(JANUS)/
$(JANUS)/wootric-sdk.js: wootric-sdk.js
	sudo cp wootric-sdk.js $(JANUS)/
$(JANUS)/zoom-components.js: zoom-components.js
	sudo cp zoom-components.js $(JANUS)/
$(JANUS)/all.css: all.css
	sudo cp all.css $(JANUS)/
$(JANUS)/meeting_delete_dialog.css: meeting_delete_dialog.css
	sudo cp meeting_delete_dialog.css $(JANUS)/
$(JANUS)/meetings.css: meetings.css
	sudo cp meetings.css $(JANUS)/
$(JANUS)/notification.css: notification.css
	sudo cp notification.css $(JANUS)/
$(JANUS)/popup-captcha.css: popup-captcha.css
	sudo cp popup-captcha.css $(JANUS)/
$(JANUS)/select2.css: select2.css
	sudo cp select2.css $(JANUS)/
$(JANUS)/zoom-components.css: zoom-components.css
	sudo cp zoom-components.css $(JANUS)/
$(JANUS)/RoomLogo.png: RoomLogo.png
	sudo cp RoomLogo.png $(JANUS)/
$(JANUS)/pay_us_meow.png: pay_us_meow.png
	sudo cp pay_us_meow.png $(JANUS)/
$(JANUS)/user.png: user.png
	sudo cp user.png $(JANUS)/
$(JANUS)/csrf_js: csrf_js
	sudo cp csrf_js $(JANUS)/
