JANUS=/var/www/html/janus/audio

default: \
	$(JANUS)/household_telephone_digital_ring_002.mp3 \
	$(JANUS)/household_telephone_digital_ring_back.mp3 \
	$(JANUS)/household_telephone_digital_ring_back.wav

$(JANUS)/household_telephone_digital_ring_002.mp3: household_telephone_digital_ring_002.mp3
	sudo cp household_telephone_digital_ring_002.mp3 $(JANUS)/
$(JANUS)/household_telephone_digital_ring_back.mp3: household_telephone_digital_ring_back.mp3
	sudo cp household_telephone_digital_ring_back.mp3 $(JANUS)/
$(JANUS)/household_telephone_digital_ring_back.wav: household_telephone_digital_ring_back.wav
	sudo cp household_telephone_digital_ring_back.wav $(JANUS)/
