HOTROOM=/var/www/html/hotroom/images

default: \
	$(HOTROOM)/icon_mail.png \
	$(HOTROOM)/icon_nav_hostmeeting.png \
	$(HOTROOM)/icon_nav_profile.png \
	$(HOTROOM)/icon_nav_schedule.png \
	$(HOTROOM)/icon_nav_sipcall.png \
	$(HOTROOM)/icon_nav_videocall.png \
	$(HOTROOM)/icon_nav_voicemail.png \
	$(HOTROOM)/img_list_ttl.png \
	$(HOTROOM)/img_profile.png \
	$(HOTROOM)/logo.png \
	$(HOTROOM)/online.png \
	$(HOTROOM)/outlook.png \
	$(HOTROOM)/chrome.gif \
	$(HOTROOM)/firefox.gif \
	$(HOTROOM)/menu_3_line.png \
	$(HOTROOM)/recording.png \
	$(HOTROOM)/rec-start-300x300.png \
	$(HOTROOM)/rec-stop.png \
	$(HOTROOM)/close_cross_icon.png \
	$(HOTROOM)/icons8-info.svg \
	$(HOTROOM)/ico_bidModal_hide_L.png

$(HOTROOM)/icon_mail.png: icon_mail.png
	sudo cp icon_mail.png $(HOTROOM)/
$(HOTROOM)/icon_nav_hostmeeting.png: icon_nav_hostmeeting.png
	sudo cp icon_nav_hostmeeting.png $(HOTROOM)/
$(HOTROOM)/icon_nav_profile.png: icon_nav_profile.png
	sudo cp icon_nav_profile.png $(HOTROOM)/
$(HOTROOM)/icon_nav_schedule.png: icon_nav_schedule.png
	sudo cp icon_nav_schedule.png $(HOTROOM)/
$(HOTROOM)/icon_nav_sipcall.png: icon_nav_sipcall.png
	sudo cp icon_nav_sipcall.png $(HOTROOM)/
$(HOTROOM)/icon_nav_videocall.png: icon_nav_videocall.png
	sudo cp icon_nav_videocall.png $(HOTROOM)/
$(HOTROOM)/icon_nav_voicemail.png: icon_nav_voicemail.png
	sudo cp icon_nav_voicemail.png $(HOTROOM)/
$(HOTROOM)/img_list_ttl.png: img_list_ttl.png
	sudo cp img_list_ttl.png $(HOTROOM)/
$(HOTROOM)/img_profile.png: img_profile.png
	sudo cp img_profile.png $(HOTROOM)/
$(HOTROOM)/logo.png: logo.png
	sudo cp logo.png $(HOTROOM)/
$(HOTROOM)/online.png: online.png
	sudo cp online.png $(HOTROOM)/
$(HOTROOM)/outlook.png: outlook.png
	sudo cp outlook.png $(HOTROOM)/
$(HOTROOM)/chrome.gif: chrome.gif
	sudo cp chrome.gif $(HOTROOM)/
$(HOTROOM)/firefox.gif: firefox.gif
	sudo cp firefox.gif $(HOTROOM)/

$(HOTROOM)/menu_3_line.png: ../../php/images/menu_3_line.png
	sudo cp ../../php/images/menu_3_line.png $(HOTROOM)/
$(HOTROOM)/recording.png: ../../php/images/recording.png
	sudo cp ../../php/images/recording.png $(HOTROOM)/
$(HOTROOM)/rec-start-300x300.png: ../../php/images/rec-start-300x300.png
	sudo cp ../../php/images/rec-start-300x300.png $(HOTROOM)/
$(HOTROOM)/rec-stop.png: ../../php/images/rec-stop.png
	sudo cp ../../php/images/rec-stop.png $(HOTROOM)/
$(HOTROOM)/close_cross_icon.png: ../../php/images/close_cross_icon.png
	sudo cp ../../php/images/close_cross_icon.png $(HOTROOM)/
$(HOTROOM)/icons8-info.svg: ../../php/images/icons8-info.svg
	sudo cp ../../php/images/icons8-info.svg $(HOTROOM)/
$(HOTROOM)/ico_bidModal_hide_L.png: ../../php/images/ico_bidModal_hide_L.png
	sudo cp ../../php/images/ico_bidModal_hide_L.png $(HOTROOM)/
