HOTROOM=/var/www/html/hotroom/js

default: \
	$(HOTROOM)/common.js \
	$(HOTROOM)/fileupload.js \
	$(HOTROOM)/jquery-3.3.1.min.js \
	$(HOTROOM)/jquery.modal.js \
	$(HOTROOM)/jquery.md5.js \
	$(HOTROOM)/janus.js \
	$(HOTROOM)/jscd.js \
	$(HOTROOM)/registerServiceWorker.js \
	$(HOTROOM)/roomadmin.js \
	$(HOTROOM)/sip.js \
	$(HOTROOM)/textroom.js \
	$(HOTROOM)/videocall.js \
	$(HOTROOM)/voicemail.js \
	$(HOTROOM)/room.js

$(HOTROOM)/common.js: common.js
	sudo cp common.js $(HOTROOM)/
$(HOTROOM)/fileupload.js: fileupload.js
	sudo cp fileupload.js $(HOTROOM)/
$(HOTROOM)/janus.js: janus.js
	sudo cp janus.js $(HOTROOM)/
$(HOTROOM)/jquery-3.3.1.min.js: jquery-3.3.1.min.js
	sudo cp jquery-3.3.1.min.js $(HOTROOM)/
$(HOTROOM)/jquery.modal.js: jquery.modal.js
	sudo cp jquery.modal.js $(HOTROOM)/
$(HOTROOM)/jquery.md5.js: jquery.md5.js
	sudo cp jquery.md5.js $(HOTROOM)/

$(HOTROOM)/jscd.js: ../../php/jscd.js
	sudo cp ../../php/jscd.js $(HOTROOM)/
$(HOTROOM)/registerServiceWorker.js: ../../php/registerServiceWorker.js
	sudo cp ../../php/registerServiceWorker.js $(HOTROOM)/
$(HOTROOM)/roomadmin.js: ../../php/roomadmin.js
	sudo cp ../../php/roomadmin.js $(HOTROOM)/
$(HOTROOM)/sip.js: ../../php/sip.js
	sudo cp ../../php/sip.js $(HOTROOM)/
$(HOTROOM)/textroom.js: ../../php/textroom.js
	sudo cp ../../php/textroom.js $(HOTROOM)/
$(HOTROOM)/videocall.js: ../../php/videocall.js
	sudo cp ../../php/videocall.js $(HOTROOM)/
$(HOTROOM)/voicemail.js: ../../php/voicemail.js
	sudo cp ../../php/voicemail.js $(HOTROOM)/
$(HOTROOM)/room.js: ../../php/room.js
	sudo cp ../../php/room.js $(HOTROOM)/
