JANUS=/var/www/html/janus/index_files

default: \
	$(JANUS)/all.js \
	$(JANUS)/api.js \
	$(JANUS)/captcha.js \
	$(JANUS)/captcha_002.js \
	$(JANUS)/embed.js \
	$(JANUS)/fileupload.js \
	$(JANUS)/jquery.SB.js \
	$(JANUS)/jquery.jcrop.js \
	$(JANUS)/jquery.modal.js \
	$(JANUS)/jquery.validate.js \
	$(JANUS)/jquery_002.js \
	$(JANUS)/jstz.js \
	$(JANUS)/lodash.js \
	$(JANUS)/notification.js \
	$(JANUS)/pbxSideMenu.js \
	$(JANUS)/popup-captcha.js \
	$(JANUS)/profile.js \
	$(JANUS)/recaptcha__ja.js \
	$(JANUS)/selectWoo.js \
	$(JANUS)/snippet.js \
	$(JANUS)/vue.js \
	$(JANUS)/wootric-sdk.js \
	$(JANUS)/zoom-components.js \
	$(JANUS)/captcha.css \
	$(JANUS)/all.css \
	$(JANUS)/meeting.css \
	$(JANUS)/meeting_delete_dialog.css \
	$(JANUS)/notification.css \
	$(JANUS)/popup-captcha.css \
	$(JANUS)/selectWoo.css \
	$(JANUS)/zm-form.css \
	$(JANUS)/zoom-components.css \
	$(JANUS)/RoomLogo.png \
	$(JANUS)/pay_us_meow.png \
	$(JANUS)/user.png \
	$(JANUS)/csrf_js

$(JANUS)/all.js: all.js
	sudo cp all.js $(JANUS)/
$(JANUS)/api.js: api.js
	sudo cp api.js $(JANUS)/
$(JANUS)/captcha.js: captcha.js
	sudo cp captcha.js $(JANUS)/
$(JANUS)/captcha_002.js: captcha_002.js
	sudo cp captcha_002.js $(JANUS)/
$(JANUS)/embed.js: embed.js
	sudo cp embed.js $(JANUS)/
$(JANUS)/fileupload.js: fileupload.js
	sudo cp fileupload.js $(JANUS)/
$(JANUS)/jquery.SB.js: jquery.SB.js
	sudo cp jquery.SB.js $(JANUS)/
$(JANUS)/jquery.jcrop.js: jquery.jcrop.js
	sudo cp jquery.jcrop.js $(JANUS)/
$(JANUS)/jquery.modal.js: jquery.modal.js
	sudo cp jquery.modal.js $(JANUS)/
$(JANUS)/jquery.validate.js: jquery.validate.js
	sudo cp jquery.validate.js $(JANUS)/
$(JANUS)/jquery_002.js: jquery_002.js
	sudo cp jquery_002.js $(JANUS)/
$(JANUS)/jstz.js: jstz.js
	sudo cp jstz.js $(JANUS)/
$(JANUS)/lodash.js: lodash.js
	sudo cp lodash.js $(JANUS)/
$(JANUS)/notification.js: notification.js
	sudo cp notification.js $(JANUS)/
$(JANUS)/pbxSideMenu.js: pbxSideMenu.js
	sudo cp pbxSideMenu.js $(JANUS)/
$(JANUS)/popup-captcha.js: popup-captcha.js
	sudo cp popup-captcha.js $(JANUS)/
$(JANUS)/profile.js: profile.js
	sudo cp profile.js $(JANUS)/
$(JANUS)/recaptcha__ja.js: recaptcha__ja.js
	sudo cp recaptcha__ja.js $(JANUS)/
$(JANUS)/selectWoo.js: selectWoo.js
	sudo cp selectWoo.js $(JANUS)/
$(JANUS)/snippet.js: snippet.js
	sudo cp snippet.js $(JANUS)/
$(JANUS)/vue.js: vue.js
	sudo cp vue.js $(JANUS)/
$(JANUS)/wootric-sdk.js: wootric-sdk.js
	sudo cp wootric-sdk.js $(JANUS)/
$(JANUS)/zoom-components.js: zoom-components.js
	sudo cp zoom-components.js $(JANUS)/
$(JANUS)/captcha.css: captcha.css
	sudo cp captcha.css $(JANUS)/
$(JANUS)/all.css: all.css
	sudo cp all.css $(JANUS)/
$(JANUS)/meeting.css: meeting.css
	sudo cp meeting.css $(JANUS)/
$(JANUS)/meeting_delete_dialog.css: meeting_delete_dialog.css
	sudo cp meeting_delete_dialog.css $(JANUS)/
$(JANUS)/notification.css: notification.css
	sudo cp notification.css $(JANUS)/
$(JANUS)/popup-captcha.css: popup-captcha.css
	sudo cp popup-captcha.css $(JANUS)/
$(JANUS)/selectWoo.css: selectWoo.css
	sudo cp selectWoo.css $(JANUS)/
$(JANUS)/zm-form.css: zm-form.css
	sudo cp zm-form.css $(JANUS)/
$(JANUS)/zoom-components.css: zoom-components.css
	sudo cp zoom-components.css $(JANUS)/
$(JANUS)/RoomLogo.png: RoomLogo.png
	sudo cp RoomLogo.png $(JANUS)/
$(JANUS)/pay_us_meow.png: pay_us_meow.png
	sudo cp pay_us_meow.png $(JANUS)/
$(JANUS)/user.png: user.png
	sudo cp user.png $(JANUS)/
$(JANUS)/csrf_js: csrf_js
	sudo cp csrf_js $(JANUS)/
